services:
  app:
    container_name: misell
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - logs:/app/logs
      - temp:/app/temp

volumes:
  logs:
  temp: